server:
  port: 8080
  address: localhost
  error:
    whitelabel:
      enabled: false



spring:

  datasource:
    username: C##AmusementPark
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: password123

  jpa:
    hibernate:
      ddl-auto: update   # or none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsOrClauseBulkIdStrategy
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: admin-panel
            uri: lb://admin-panel
            predicates:
              - Path=/api/v1/admin-panel/**
            filters:
              - StripPrefix=3
          - id: user-panel
            uri: lb://user-panel
            predicates:
              - Path=/api/v1/user-panel/**
            filters:
              - StripPrefix=3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

logging:
  level:
    root: INFO
    org.springframework.web:
      gateway: TRACE
      route:
        RouteDefinitionRouteLocator: INFO

custom:
  security:
    jwt:
      secret: dac6c0036c5410a38089cb7837e60fa1e388ccaea8f910f65934cf09b6f28bb1