version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracleBADA
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
    stdin_open: true
    tty: true

volumes:
  oracle-data:
    driver: local
