server:
  port: 8082
  error:
    whitelabel:
      enabled: false


spring:
  application:
    name: admin-panel

  datasource:
    username: C##AmusementPark
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

custom:
  security:
    jwt:
      secret: dac6c0036c5410a38089cb7837e60fa1e388ccaea8f910f65934cf09b6f28bb1
