server:
  port: 8082

spring:
  application:
    name: admin-panel

  datasource:
    username: C##AmusementPark
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

custom:
  security:
    jwt:
      secret: 1e2d1ca930a830460333a4c919465cbc6511d73776a00792138daaa22e880540
