server:
  port: 8082

spring:
  application:
    name: admin-panel
  datasource:
    username: login
    url: jdbc:postgresql://localhost:5432/amusement-park
    password: haslo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true