server:
  port: 8081

spring:
  application:
    name: user-panel
  datasource:
    username: C##AmusementPark
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: password123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true